In [1]:
#importing excel data into python
import pandas as pd
import xlrd

datasheet1=pd.read_excel('Optimisation_Exercise.xlsx',sheet_name='distances')
print(datasheet1)
datasheet2=pd.read_excel('Optimisation_Exercise.xlsx',sheet_name='cost_matrix')
print(datasheet2)


xls = pd.ExcelFile('Optimisation_Exercise.xlsx')
sheets = xls.sheet_names
print(sheets)

for i in range(len(sheets)):
    print(sheets[i])

print('stop')

df2=pd.DataFrame(datasheet1,columns=['Cityname'])
#print('dataset2',df2.values)
A=df2.values
print(A)

            Cityname  Barcelona  Belgrade   Berlin  Brussels  Bucharest  \
0          Barcelona       0.00   1528.13  1497.61   1062.89    1968.42
1           Belgrade    1528.13      0.00   999.25   1372.59     447.34
2             Berlin    1497.61    999.25     0.00    651.62    1293.40
3           Brussels    1062.89   1372.59   651.62      0.00    1769.69
4          Bucharest    1968.42    447.34  1293.40   1769.69       0.00
5           Budapest    1498.79    316.41   689.06   1131.52     639.77
6         Copenhagen    1757.54   1327.24   354.03    766.67    1571.54
7             Dublin    1469.29   2145.39  1315.16    773.20    2534.72
8            Hamburg    1471.78   1229.93   254.51    489.76    1544.17
9           Istanbul    2230.42    809.48  1735.01   2178.85     445.62
10              Kiev    2391.06    976.02  1204.00   1836.20     744.44
11            London    1137.67   1688.97   929.97    318.72    2088.42
12            Madrid     504.64   2026.94  1867.69   1314.30    2469.71
13             Milan     725.12    885.32   840.72    696.61    1331.46
14            Moscow    3006.93   1710.99  1607.99   2253.26    1497.56
15            Munich    1054.55    773.33   501.97    601.87    1186.37
16             Paris     831.59   1445.70   876.96    261.29    1869.95
17            Prague    1353.90    738.10   280.34    721.08    1076.82
18              Rome     856.69    721.55  1181.67   1171.34    1137.38
19  Saint Petersburg    2813.02   1797.75  1319.62   1903.66    1740.39
20             Sofia    1745.55    329.46  1318.67   1697.83     296.68
21         Stockholm    2276.51   1620.96   810.38   1280.88    1742.25
22            Vienna    1347.43    489.28   523.61    914.81     855.32
23            Warsaw    1862.33    826.66   516.06   1159.85     946.12

    Budapest  Copenhagen   Dublin  Hamburg  ...   Moscow   Munich    Paris  \
0    1498.79     1757.54  1469.29  1471.78  ...  3006.93  1054.55   831.59
1     316.41     1327.24  2145.39  1229.93  ...  1710.99   773.33  1445.70
2     689.06      354.03  1315.16   254.51  ...  1607.99   501.97   876.96
3    1131.52      766.67   773.20   489.76  ...  2253.26   601.87   261.29
4     639.77     1571.54  2534.72  1544.17  ...  1497.56  1186.37  1869.95
5       0.00     1011.31  1894.95   927.92  ...  1565.19   563.93  1247.61
6    1011.31        0.00  1238.38   287.97  ...  1558.52   838.00  1025.90
7    1894.95     1238.38     0.00  1073.36  ...  2792.41  1374.91   776.83
8     927.92      287.97  1073.36     0.00  ...  1779.93   610.17   744.63
9    1064.76     2017.17  2950.11  1983.75  ...  1753.97  1582.16  2253.98
10    894.29     1326.33  2513.69  1440.34  ...   756.61  1391.36  2022.76
11   1450.12      955.13   462.60   720.12  ...  2498.32   916.23   340.55
12   1975.38     2071.75  1449.96  1785.33  ...  3437.70  1484.53  1053.40
13    788.56     1157.89  1413.37   900.01  ...  2283.19   348.89   641.31
14   1565.19     1558.52  2792.41  1779.93  ...     0.00  1957.15  2484.92
15    563.93      838.00  1374.91   610.17  ...  1957.15     0.00   685.14
16   1247.61     1025.90   776.83   744.63  ...  2484.92   685.14     0.00
17    443.26      633.05  1465.61   492.25  ...  1664.04   300.16   885.38
18    811.11     1529.69  1882.22  1307.51  ...  2374.26   698.04  1105.76
19   1556.51     1143.40  2314.19  1414.16  ...   632.59  1773.83  2157.99
20    629.63     1635.54  2471.02  1554.82  ...  1777.35  1096.54  1758.03
21   1316.59      521.68  1626.56   809.65  ...  1227.38  1311.80  1541.83
22    216.98      868.87  1680.00   742.79  ...  1669.22   354.42  1033.73
23    545.29      667.80  1823.72   750.49  ...  1149.41   809.02  1365.91

     Prague     Rome  Saint Petersburg    Sofia  Stockholm   Vienna   Warsaw
0   1353.90   856.69           2813.02  1745.55    2276.51  1347.43  1862.33
1    738.10   721.55           1797.75   329.46    1620.96   489.28   826.66
2    280.34  1181.67           1319.62  1318.67     810.38   523.61   516.06
3    721.08  1171.34           1903.66  1697.83    1280.88   914.81  1159.85
4   1076.82  1137.38           1740.39   296.68    1742.25   855.32   946.12
5    443.26   811.11           1556.51   629.63    1316.59   216.98   545.29
6    633.05  1529.69           1143.40  1635.54     521.68   868.87   667.80
7   1465.61  1882.22           2314.19  2471.02    1626.56  1680.00  1823.72
8    492.25  1307.51           1414.16  1554.82     809.65   742.79   750.49
9   1507.55  1373.81           2099.29   502.61    2171.65  1273.88  1386.08
10  1138.61  1673.74           1051.39  1020.76    1265.79  1052.76   690.12
11  1034.57  1431.21           2093.69  2012.70    1431.07  1233.48  1445.85
12  1773.73  1360.80           3183.43  2250.10    2591.53  1807.09  2288.42
13   646.04   476.00           2122.15  1166.83    1650.12   623.36  1143.01
14  1664.04  2374.26            632.59  1777.35    1227.38  1669.22  1149.41
15   300.16   698.04           1773.83  1096.54    1311.80   354.42   809.02
16   885.38  1105.76           2157.99  1758.03    1541.83  1033.73  1365.91
17     0.00   922.00           1476.73  1064.43    1052.85   250.71   514.69
18   922.00     0.00           2339.22   894.06    1974.79   763.26  1316.24
19  1476.73  2339.22              0.00  1969.82     688.33  1577.56  1023.41
20  1064.43   894.06           1969.82     0.00    1884.91   817.45  1076.99
21  1052.85  1974.79            688.33  1884.91       0.00  1241.90   808.14
22   250.71   763.26           1577.56   817.45    1241.90     0.00   557.43
23   514.69  1316.24           1023.41  1076.99     808.14   557.43     0.00

[24 rows x 25 columns]
   Super Market  Warehouse 1(USD)  Warehouse 2(USD)
0             1              2000              3000
1             2              4000              1000
2             3              5000              3000
3             4              2000              2000
4             5              1000              3000
['distances', 'cost_matrix']
distances
cost_matrix
stop
[['Barcelona']
 ['Belgrade']
 ['Berlin']
 ['Brussels']
 ['Bucharest']
 ['Budapest']
 ['Copenhagen']
 ['Dublin']
 ['Hamburg']
 ['Istanbul']
 ['Kiev']
 ['London']
 ['Madrid']
 ['Milan']
 ['Moscow']
 ['Munich']
 ['Paris']
 ['Prague']
 ['Rome']
 ['Saint Petersburg']
 ['Sofia']
 ['Stockholm']
 ['Vienna']
 ['Warsaw']]